spring:
  application:
    name: QuestionService

  datasource:
    url: jdbc:mysql://localhost:3306/exam_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

eureka:
  instance:
    client:
      # URL of the Eureka server to which the client should register itself.
      # In this case, the Eureka server is running on the local machine at port 8761.
      # The 'defaultZone' is the default URL for Eureka's REST API used for registering and discovering services.
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
