spring:
  application:
    name: QUIZ-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/exam_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Automatically updates the database schema to match your entity classes. Does not drop or delete existing data or tables.

server:
  port: 8081

eureka:
  instance:
    client:
      serverUrl:
        # URL of the Eureka server to which the client should register itself.
        # In this case, the Eureka server is running on the local machine at port 8761.
        # The 'defaultZone' is the default URL for Eureka's REST API used for registering and discovering services.
        defaultZone: http://localhost:8761/eureka/