spring:
  application:
    name: QuizService

  datasource:
    url: jdbc:mysql://localhost:3306/exam_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Automatically updates the database schema to match your entity classes. Does not drop or delete existing data or tables.

server:
  port: 8081